// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arbmfohldajuimrwykzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyYm1mb2hsZGFqdWltcnd5a3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTE0MTQsImV4cCI6MjA2NDQ4NzQxNH0.QjqzrYzmE6u_yZ50ilxnNd8QSxXwrMrJ6IJ6qI8RpgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);